comment_width = 100
condense_wildcard_suffixes = true
edition = "2021"
error_on_line_overflow = true
error_on_unformatted = true
fn_single_line = true
format_macro_matchers = true
hard_tabs = true
hex_literal_case = "Lower"
imports_granularity = "One"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "One"
single_line_if_else_max_width = 100
struct_lit_single_line = false
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
version = "Two"
wrap_comments = true

