[package]
name = "gokz_rs"
version = "0.6.7"
edition = "2021"
description = "Rust wrapper for the CS:GO KZ GlobalAPI"
license-file = "./LICENSE"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
chrono = { version = "0.4" }
regex = { version = "1.6" }
futures = { version = "0.3.5" }

