[package]
name = "gokz_rs"
version = "0.10.5"
edition = "2021"
description = "Rust wrapper for the CS:GO KZ GlobalAPI"
license = "MIT"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
regex = "1.6"
futures = "0.3.5"
log = "0.4"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
env_logger = "0.10"
