[package]
name = "gokz_rs"
version = "0.12.0"
description = "Rust wrapper for the CS:GO KZ GlobalAPI"
authors = ["AlphaKeks <alphakeks@dawn.sh>"]
edition = "2021"
readme = "./README.md"
repository = "https://github.com/AlphaKeks/gokz.rs"
license = "MIT"
publish = true

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
regex = "1.6"
futures = "0.3.5"
log = "0.4"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.10"
test-log = "0.2"
anyhow = "1"
