[package]
name = "gokz_rs"
version = "0.8.2"
edition = "2021"
description = "Rust wrapper for the CS:GO KZ GlobalAPI"
license-file = "./LICENSE"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
regex = "1.6"
futures = "0.3.5"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
