[package]
name = "gokz_rs"
version = "0.16.3"
description = "CS:GO KZ in Rust."
authors = ["AlphaKeks <alphakeks@dawn.sh>"]
edition = "2021"
readme = "./README.md"
repository = "https://github.com/AlphaKeks/gokz.rs"
license = "MIT"
publish = true

[dependencies]
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }

regex = "1.6"
chrono = { version = "0.4", optional = true }
lazy_static = "1.4"

reqwest = { version = "0.11", features = ["json", "blocking"], optional = true }
futures = { version = "0.3.5", optional = true }

[dev-dependencies]
color-eyre = "0.6"
log = "0.4"
env_logger = "0.10"
test-log = { version = "0.2", features = ["log"] }

tokio = { version = "1", features = ["full"] }

[features]
reqwest = ["dep:reqwest"]
chrono = ["dep:chrono"]
global_api = ["reqwest", "chrono", "dep:futures"]
kzgo_api = ["reqwest", "chrono"]
schnose_api = ["reqwest", "chrono"]
