[package]
name = "gokz_rs"
version = "0.16.0"
description = "CS:GO KZ in Rust."
authors = ["AlphaKeks <alphakeks@dawn.sh>"]
edition = "2021"
readme = "./README.md"
repository = "https://github.com/AlphaKeks/gokz.rs"
license = "MIT"
publish = true

[dependencies]
log = "0.4"

reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

chrono = "0.4"
regex = "1.6"

futures = "0.3.5"

[dev-dependencies]
color-eyre = "0.6"
log = "0.4"
env_logger = "0.10"
test-log = { version = "0.2", features = ["log"] }

tokio = { version = "1", features = ["full"] }
