edition = "2021"

merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
use_field_init_shorthand = true
use_try_shorthand = true

# indentation
hard_tabs = true

# line width
max_width = 100
array_width = 40
chain_width = 40

# layout
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
