#![doc = include_str!("../README.md")]
#![deny(missing_docs)]
#![deny(clippy::correctness, clippy::perf)]
#![warn(rust_2018_idioms, missing_debug_implementations)]
#![warn(clippy::style, clippy::complexity, clippy::cognitive_complexity)]
